# Generated by Django 4.0.4 on 2022-05-31 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_one', '0005_blog_blog_picture_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 11, 0, 48, 809870)),
        ),
    ]
